[project]
name = "MGUI_QEMU"
version = "0.1.0"
description = "Modern GUI for QEMU"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=5.9.0",
    "pyside6>=6.6.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.0.0",
]