name: Build MGUI_QEMU for Windows

on: 
  push:
    branches: [ main ] # Збирати тільки при пуші в основну гілку (опціонально)
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Оновив до v4 (найновіша)

      - name: Set up Python
        uses: actions/setup-python@v5 # Оновив до v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 psutil pyinstaller

      - name: Build EXE
        run: |
          # Додаємо --add-data, щоб іконка підтягнулася всередину EXE
          # На Windows у PyInstaller розділювач - крапка з комою (;)
          pyinstaller --noconfirm --onefile --windowed --name "MGUI_QEMU" --add-data "icon.txt;." main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Оновив до v4
        with:
          name: MGUI_QEMU_Windows_Build
          path: dist/MGUI_QEMU.exe
